title: Peter Binkley
email: peter.binkley@ualberta.ca
description: >- # this means to ignore newlines until "baseurl:"
  Various projects under pbinkley's GitHub account
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pbinkley.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pabinkley
github_username:  pbinkley

theme: jekyll-theme-slate

github:
  is_project_page: false
